Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
LSP Notebooks experiment is disabled -- not in treatment group
> conda info --json
Python interpreter path: /usr/bin/python3
> /bin/python ./.vscode-server/extensions/ms-python.python-2022.8.0/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2022.8.0/pythonFiles/interpreterInfo.py
> /usr/bin/python ./.vscode-server/extensions/ms-python.python-2022.8.0/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2022.8.0/pythonFiles/interpreterInfo.py
[ERROR 2022-5-24 10:8:13.350]: [
  'Failed to start language server, Class name = h, completed in 827ms, has a falsy return value, Arg 1: <Uri:/home/pi>, Arg 2: {"id":"/usr/bin/python3","sysPrefix":"/usr","envType":"Global","envName":"","envPath":"","path":"/usr/bin/python3","architecture":3,"sysVersion":"3.9.2 (default, Feb 28 2021, 17:03:44) \\n[GCC 10.2.1 20210110]","version":{"raw":"3.9.2","major":3,"minor":9,"patch":2,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.2 64-bit","detailedDisplayName":"Python 3.9.2 64-bit"}, Arg 3: {"documentSelector":[{"scheme":"file","language":"python"},{"scheme":"untitled","language":"python"},{"scheme":"vscode-notebook","language":"python"},{"scheme":"vscode-notebook-cell","language":"python"},{"scheme":"vscode-interactive-input","language":"python"}],"synchronize":{"configurationSection":"python"},"outputChannel":{"name":"Python Language Server"},"revealOutputChannelOn":4,"initializationOptions":{"experimentationSupport":true,"trustedWorkspaceSupport":true,"lspNotebooksSupport":false},"middleware":{"serviceContainer":{"container":{"options":{"autoBindInjectable":false,"defaultScope":"Transient","skipBaseClassChecks":true},"id":0,"_bindingDictionary":{"_map":{}},"_snapshots":[],"_middleware":null,"parent":null,"_metadataReader":{}}},"serverVersion":"2022.6.30","lastCaptured":{},"nextWindow":0,"eventCount":0,"workspace":{},"connectedPromise":{"scope":null,"_resolved":false,"_rejected":false,"_promise":{}},"eventName":"LANGUAGE_SERVER.REQUEST","lspNotebooksExperiment":{"serviceContainer":{"container":{"options":{"autoBindInjectable":false,"defaultScope":"Transient","skipBaseClassChecks":true},"id":0,"_bindingDictionary":{"_map":{}},"_snapshots":[],"_middleware":null,"parent":null,"_metadataReader":{}}},"configurationService":{"serviceContainer":{"container":{"options":{"autoBindInjectable":false,"defaultScope":"Transient","skipBaseClassChecks":true},"id":0,"_bindingDictionary":{"_map":{}},"_snapshots":[],"_middleware":null,"parent":null,"_metadataReader":{}}},"workspaceService":{}},"supportedWorkspaceTypes":{"untrustedWorkspace":true,"virtualWorkspace":true},"isJupyterInstalled":true,"isInExperiment":false},"notebookAddon":{}},"connectionOptions":{"cancellationStrategy":{"_sender":{"folderName":"c7c9d0b7575c24a95c830def302e5c14a61f46517b"}}}}, Return Value: undefined',
  [s [Error]: Pending response rejected since connection got disposed
  	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2114551)
  	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2165913)
  	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166191)
  	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2320852)
  	at /home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166001
  	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
  	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
  	at Z (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2102907)
  	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
  	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
  	at d.fireClose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2124847)
  	at ChildProcess.<anonymous> (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2135840)
  	at ChildProcess.emit (node:events:402:35)
  	at maybeClose (node:internal/child_process:1064:16)
  	at Socket.<anonymous> (node:internal/child_process:450:11)
  	at Socket.emit (node:events:390:28)
  	at Pipe.<anonymous> (node:net:687:12)] {
    code: -32097,
    data: undefined
  }
]
[ERROR 2022-5-24 10:8:13.357]: [
  'Starting language server, Class name = d, completed in 840ms, has a falsy return value, , Return Value: undefined',
  [s [Error]: Pending response rejected since connection got disposed
  	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2114551)
  	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2165913)
  	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166191)
  	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2320852)
  	at /home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166001
  	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
  	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
  	at Z (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2102907)
  	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
  	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
  	at d.fireClose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2124847)
  	at ChildProcess.<anonymous> (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2135840)
  	at ChildProcess.emit (node:events:402:35)
  	at maybeClose (node:internal/child_process:1064:16)
  	at Socket.<anonymous> (node:internal/child_process:450:11)
  	at Socket.emit (node:events:390:28)
  	at Pipe.<anonymous> (node:net:687:12)] {
    code: -32097,
    data: undefined
  }
]
[ERROR 2022-5-24 10:8:13.361]: [
  'Failed to start language server, Class name = d, completed in 847ms, has a falsy return value, Arg 1: <Uri:/home/pi>, Arg 2: {"id":"/usr/bin/python3","sysPrefix":"/usr","envType":"Global","envName":"","envPath":"","path":"/usr/bin/python3","architecture":3,"sysVersion":"3.9.2 (default, Feb 28 2021, 17:03:44) \\n[GCC 10.2.1 20210110]","version":{"raw":"3.9.2","major":3,"minor":9,"patch":2,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.2 64-bit","detailedDisplayName":"Python 3.9.2 64-bit"}, Return Value: undefined',
  [s [Error]: Pending response rejected since connection got disposed
  	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2114551)
  	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2165913)
  	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166191)
  	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2320852)
  	at /home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166001
  	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
  	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
  	at Z (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2102907)
  	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
  	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
  	at d.fireClose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2124847)
  	at ChildProcess.<anonymous> (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2135840)
  	at ChildProcess.emit (node:events:402:35)
  	at maybeClose (node:internal/child_process:1064:16)
  	at Socket.<anonymous> (node:internal/child_process:450:11)
  	at Socket.emit (node:events:390:28)
  	at Pipe.<anonymous> (node:net:687:12)] {
    code: -32097,
    data: undefined
  }
]
[ERROR 2022-5-24 10:8:13.363]: [
  'Failed to activate a workspace, Class name = f, completed in 1680ms, has a falsy return value, Arg 1: <Uri:/home/pi/master.py>, Return Value: undefined',
  [s [Error]: Pending response rejected since connection got disposed
  	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2114551)
  	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2165913)
  	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166191)
  	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2320852)
  	at /home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166001
  	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
  	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
  	at Z (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2102907)
  	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
  	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
  	at d.fireClose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2124847)
  	at ChildProcess.<anonymous> (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2135840)
  	at ChildProcess.emit (node:events:402:35)
  	at maybeClose (node:internal/child_process:1064:16)
  	at Socket.<anonymous> (node:internal/child_process:450:11)
  	at Socket.emit (node:events:390:28)
  	at Pipe.<anonymous> (node:net:687:12)] {
    code: -32097,
    data: undefined
  }
]
[ERROR 2022-5-24 10:8:13.366]: Failure during activation. [s [Error]: Pending response rejected since connection got disposed
	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2114551)
	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2165913)
	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166191)
	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2320852)
	at /home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166001
	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
	at Z (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2102907)
	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
	at d.fireClose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2124847)
	at ChildProcess.<anonymous> (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2135840)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  code: -32097,
  data: undefined
}
[ERROR 2022-5-24 10:8:13.366]: sendStartupTelemetry() failed. [s [Error]: Pending response rejected since connection got disposed
	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2114551)
	at Object.dispose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2165913)
	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166191)
	at S.handleConnectionClosed (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2320852)
	at /home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2166001
	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
	at Z (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2102907)
	at invoke (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2116263)
	at o.fire (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2117028)
	at d.fireClose (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2124847)
	at ChildProcess.<anonymous> (/home/pi/.vscode-server/extensions/ms-python.python-2022.8.0/out/client/extension.js:2:2135840)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  code: -32097,
  data: undefined
}
