[2022-06-24 11:17:36.214] [remoteagent] [info] Extension host agent started.
[2022-06-24 11:17:36.852] [remoteagent] [error] [127.0.0.1][f7b39765][ManagementConnection] Unknown reconnection token (never seen).
[2022-06-24 11:17:36.963] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:36.966] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:37.112] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:44.515] [remoteagent] [info] [127.0.0.1][70bd1e2e][ManagementConnection] New connection established.
[2022-06-24 11:17:44.635] [remoteagent] [info] [127.0.0.1][0e1b8459][ExtensionHostConnection] New connection established.
[2022-06-24 11:17:44.664] [remoteagent] [info] [127.0.0.1][0e1b8459][ExtensionHostConnection] <1380> Launched Extension Host Process.
[2022-06-24 11:17:45.242] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:45.273] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:45.291] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:46.370] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: inotify_add_watch on '/home/pi/.vscode-server/data/logs/20220622T083814/exthost1' failed: No such file or directory (EUNKNOWN) (path: /home/pi)
[2022-06-24 11:17:46.372] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: inotify_add_watch on '/home/pi/.vscode-server/data/logs/20220622T083814/exthost1' failed: No such file or directory
[2022-06-24 11:17:46.828] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:46.845] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:47.699] [remoteagent] [error] ["Error: Could not find pty on pty host","    at w._throwIfNoPty (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:20:5333)","    at w.updateTitle (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:20:1673)","    at Object.call (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:13:8386)","    at h.onPromise (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:12:4891)","    at h.onRawMessage (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:12:4274)","    at /home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:12:3560","    at E.invoke (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:8:145)","    at W.deliver (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:8:2271)","    at c.fire (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:8:1849)","    at process.U (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:6:35698)","    at process.emit (node:events:390:28)","    at emit (node:internal/child_process:917:12)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-06-24 11:17:47.955] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:48.254] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:17:48.848] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:22:47.529] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:27:47.758] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:32:47.935] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:37:48.160] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:42:48.530] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:47:49.416] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:52:49.690] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 11:57:50.463] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 12:02:33.563] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 12:02:51.926] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 12:07:14.915] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 12:07:52.193] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 12:12:52.372] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
